import {
  type MigrateDownArgs,
  type MigrateUpArgs,
  sql,
} from "@payloadcms/db-postgres";

/**
 * Change comments.news_id FK from ON DELETE SET NULL to ON DELETE CASCADE.
 *
 * Same bug class as 20260621_220614_fix_user_news_cascade: the `news` field on
 * Comments is `required: true` (NOT NULL), but the FK generated by the init
 * migration is ON DELETE SET NULL. Postgres cannot SET NULL on a NOT NULL
 * column, so deleting a News article that has any comment aborts the whole
 * transaction with:
 *   "null value in column news_id of relation comments violates not-null constraint"
 *
 * The visible symptom is a downstream error, because every later statement in
 * the aborted transaction fails too — e.g. the preference cleanup:
 *   delete from "payload_preferences" where "key" in ($1)
 *   -> current transaction is aborted, commands ignored until end of transaction block
 *
 * That earlier migration fixed news_analytics.article_id but missed
 * comments.news_id — this closes the gap.
 *
 * Cascade (not set null) is the right semantics: a comment on a deleted article
 * has nothing to attach to, and totalComments is a denormalized cache
 * maintained by the Comments hooks, so losing the rows with the article is fine.
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
    ALTER TABLE "comments"
      DROP CONSTRAINT IF EXISTS "comments_news_id_news_id_fk",
      ADD CONSTRAINT "comments_news_id_news_id_fk"
      FOREIGN KEY ("news_id") REFERENCES "public"."news"("id")
      ON DELETE cascade ON UPDATE no action;
  `);
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  // Reverting to SET NULL restores the broken state (NOT NULL + SET NULL);
  // it is here only for symmetry with the rest of the migration set.
  await db.execute(sql`
    ALTER TABLE "comments"
      DROP CONSTRAINT IF EXISTS "comments_news_id_news_id_fk",
      ADD CONSTRAINT "comments_news_id_news_id_fk"
      FOREIGN KEY ("news_id") REFERENCES "public"."news"("id")
      ON DELETE set null ON UPDATE no action;
  `);
}
